export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const  AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = "GET_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";


export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";

export const USERS_SELECTED = "USERS_SELECTED";
export const SHOPS_SELECTED = "SHOPS_SELECTED";
export const SERVICES_SELECTED="SERVICES_SELECTED";
export const ACCOUNT_SELECTED = "ACCOUNT_SELECTED";

export const USER_LOADED2 = "USER_LOADED2";

export const ADD_SERVICE = "ADD_SERVICE";
